/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Guerreiro;
import servicos.GuerreiroServicos;
import servicos.ServicosFactory;

/**
 *
 * @author 182310065
 */
public class JFGuerreiro extends javax.swing.JFrame {

    int idEdit;

    /**
     * Creates new form JFGuerreiro
     */
    public JFGuerreiro() {
        initComponents();
        addRowToTable();
        jbEditarGuerreiro.setVisible(false);
        jbDeletarGuerreiro.setVisible(false);
    }

    private void addRowToTable() {
        DefaultTableModel model = (DefaultTableModel) jtGuerreiro.getModel();
        model.getDataVector().removeAllElements(); 
        model.fireTableDataChanged();
        Object rowData[] = new Object[6];
        GuerreiroServicos guerreiroS = ServicosFactory.getGuerreiroServicos(); 
        for (Guerreiro guerreiro : guerreiroS.listaGuerreiros()) {
            rowData[0] = guerreiro.getId();
            rowData[1] = guerreiro.getNome();
            rowData[2] = guerreiro.getOlho();
            rowData[3] = guerreiro.isSexo() == false ? "FEMININO" : "MASCULINO";
            rowData[4] = guerreiro.getPontosDeVida();
            rowData[5] = guerreiro.getArmamento();
            model.addRow(rowData);
        }
    }//fim addRowToTable

    private void limpaCampos() {
        jtfNomeGuerreiro.setText("");
        jtfCabeloGuerreiro.setText("");
        jtfOlhoGuerreiro.setText("");
        jtfPeleGuerreiro.setText("");
        jtfArmamentoGuerreiro.setText("");
        bgSexoGuerreiro.clearSelection();
        jtfNomeGuerreiro.requestFocus();
    }

    private boolean validaInputs() {
        if (jtfNomeGuerreiro.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher o nome");
            jtfNomeGuerreiro.requestFocus();
            return false;
        }
        if (jtfCabeloGuerreiro.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher o cabelo");
            jtfCabeloGuerreiro.requestFocus();
            return false;
        }
        if (jtfOlhoGuerreiro.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher o olho");
            jtfOlhoGuerreiro.requestFocus();
            return false;
        }
        if (jtfPeleGuerreiro.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher a pele");
            jtfPeleGuerreiro.requestFocus();
            return false;
        }
        if (jtfArmamentoGuerreiro.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher o armamento");
            jtfArmamentoGuerreiro.requestFocus();
            return false;
        }
        if (!jrbFemininoGuerreiro.isSelected() && !jrbMasculinoGuerreiro.isSelected()) {
            JOptionPane.showMessageDialog(this, "Selecionar sexo");
            return false;
        }
        return true;
    }

    private void jbDefault() {
        jbSalvarGuerreiro.setText("Salvar");
        jbDeletarGuerreiro.setText("Deletar");
        jlSexoGuerreiro.setVisible(true);
        jrbFemininoGuerreiro.setVisible(true);
        jrbMasculinoGuerreiro.setVisible(true);
        jbEditarGuerreiro.setVisible(false);
        jbDeletarGuerreiro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexoGuerreiro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jtfNomeGuerreiro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfCabeloGuerreiro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfOlhoGuerreiro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfPeleGuerreiro = new javax.swing.JTextField();
        jrbFemininoGuerreiro = new javax.swing.JRadioButton();
        jrbMasculinoGuerreiro = new javax.swing.JRadioButton();
        jlSexoGuerreiro = new javax.swing.JLabel();
        jbSalvarGuerreiro = new javax.swing.JButton();
        jbLimparGuerreiro = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtGuerreiro = new javax.swing.JTable();
        jbDeletarGuerreiro = new javax.swing.JButton();
        jbEditarGuerreiro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfArmamentoGuerreiro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Guerreiro");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 255));

        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Nome:");

        jtfNomeGuerreiro.setToolTipText("Informe o nome do guerreiro.");
        jtfNomeGuerreiro.setName(""); // NOI18N

        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Cabelo:");

        jtfCabeloGuerreiro.setToolTipText("Informe a cor do cabelo do guerreiro.");

        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("Olho:");

        jtfOlhoGuerreiro.setToolTipText("Informe a cor do olho do guerreiro.");

        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("Pele:");

        jtfPeleGuerreiro.setToolTipText("Informe a cor de pele do guerreiro.");

        bgSexoGuerreiro.add(jrbFemininoGuerreiro);
        jrbFemininoGuerreiro.setForeground(new java.awt.Color(153, 153, 255));
        jrbFemininoGuerreiro.setText("Feminino");

        bgSexoGuerreiro.add(jrbMasculinoGuerreiro);
        jrbMasculinoGuerreiro.setForeground(new java.awt.Color(153, 153, 255));
        jrbMasculinoGuerreiro.setText("Masculino");

        jlSexoGuerreiro.setForeground(new java.awt.Color(153, 153, 255));
        jlSexoGuerreiro.setText("Sexo:");

        jbSalvarGuerreiro.setBackground(new java.awt.Color(204, 204, 255));
        jbSalvarGuerreiro.setForeground(new java.awt.Color(102, 102, 255));
        jbSalvarGuerreiro.setText("Salvar");
        jbSalvarGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarGuerreiroActionPerformed(evt);
            }
        });

        jbLimparGuerreiro.setBackground(new java.awt.Color(204, 204, 255));
        jbLimparGuerreiro.setForeground(new java.awt.Color(102, 102, 255));
        jbLimparGuerreiro.setText("Limpar");
        jbLimparGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparGuerreiroActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(204, 204, 255));

        jtGuerreiro.setForeground(new java.awt.Color(153, 153, 255));
        jtGuerreiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Olho", "Sexo", "HP", "Armamento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtGuerreiro.setGridColor(new java.awt.Color(204, 204, 255));
        jtGuerreiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtGuerreiroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtGuerreiro);

        jbDeletarGuerreiro.setBackground(new java.awt.Color(204, 204, 255));
        jbDeletarGuerreiro.setForeground(new java.awt.Color(102, 102, 255));
        jbDeletarGuerreiro.setText("Deletar");
        jbDeletarGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarGuerreiroActionPerformed(evt);
            }
        });

        jbEditarGuerreiro.setBackground(new java.awt.Color(204, 204, 255));
        jbEditarGuerreiro.setForeground(new java.awt.Color(102, 102, 255));
        jbEditarGuerreiro.setText("Editar");
        jbEditarGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarGuerreiroActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(153, 153, 255));
        jLabel6.setText("Armamento:");

        jtfArmamentoGuerreiro.setToolTipText("Informe a cor de pele do guerreiro.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfNomeGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtfArmamentoGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtfPeleGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jtfCabeloGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jlSexoGuerreiro))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addComponent(jtfOlhoGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jrbMasculinoGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jrbFemininoGuerreiro))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbSalvarGuerreiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbLimparGuerreiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbEditarGuerreiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbDeletarGuerreiro)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNomeGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCabeloGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtfOlhoGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfPeleGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSexoGuerreiro)
                    .addComponent(jrbFemininoGuerreiro))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jrbMasculinoGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jtfArmamentoGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbDeletarGuerreiro)
                    .addComponent(jbEditarGuerreiro)
                    .addComponent(jbLimparGuerreiro)
                    .addComponent(jbSalvarGuerreiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarGuerreiroActionPerformed
        // TODO add your handling code here:
        if (jbSalvarGuerreiro.getText().equals("Salvar")) {
            if (validaInputs()) {
                Guerreiro g = new Guerreiro();
                g.setNome(jtfNomeGuerreiro.getText().toUpperCase());
                g.setOlho(jtfOlhoGuerreiro.getText().toUpperCase());
                g.setCabelo(jtfCabeloGuerreiro.getText().toUpperCase());
                g.setPele(jtfPeleGuerreiro.getText().toUpperCase());
                g.setArmamento(jtfArmamentoGuerreiro.getText().toUpperCase());
                if (jrbFemininoGuerreiro.isSelected() || jrbMasculinoGuerreiro.isSelected()) {
                    g.setSexo(!jrbFemininoGuerreiro.isSelected());
                }
                GuerreiroServicos guerreiroS = ServicosFactory.getGuerreiroServicos();
                guerreiroS.cadastrarGuerreiro(g);
                addRowToTable();
                limpaCampos();
            }
        }//fim da condição de salvar
        else {
            Guerreiro guer = new Guerreiro();
            guer.setId(idEdit);
            guer.setNome(jtfNomeGuerreiro.getText());
            guer.setOlho(jtfOlhoGuerreiro.getText());
            guer.setCabelo(jtfCabeloGuerreiro.getText());
            guer.setPele(jtfPeleGuerreiro.getText());
            guer.setArmamento(jtfArmamentoGuerreiro.getText());
            GuerreiroServicos guerreiroS = ServicosFactory.getGuerreiroServicos();
            guerreiroS.atualizarGuerreiro(guer);
            addRowToTable();
            JOptionPane.showMessageDialog(this, "Guerreiro atualizado com sucesso!");
            jbDefault();
            limpaCampos();
        }//fim da condição de atualizar
    }//GEN-LAST:event_jbSalvarGuerreiroActionPerformed

    private void jbLimparGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparGuerreiroActionPerformed
        // TODO add your handling code here:
        limpaCampos();
    }//GEN-LAST:event_jbLimparGuerreiroActionPerformed

    private void jtGuerreiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtGuerreiroMouseClicked
        // TODO add your handling code here:
        jbEditarGuerreiro.setVisible(true);
        jbDeletarGuerreiro.setVisible(true);
    }//GEN-LAST:event_jtGuerreiroMouseClicked

    private void jbDeletarGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarGuerreiroActionPerformed
        // TODO add your handling code here:
        if (jbDeletarGuerreiro.getText().equals("Deletar")) {
            int linha = jtGuerreiro.getSelectedRow();
            int id = (int) jtGuerreiro.getValueAt(linha, 0);
            String nome = (String) jtGuerreiro.getValueAt(linha, 1);
            Object[] btnMSG = {"Sim", "Não"};
            int resp = JOptionPane.showOptionDialog(this,
                    "Deseja realmente deletar " + nome,
                    ".: Deletar :.",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.WARNING_MESSAGE,
                    null, btnMSG, btnMSG[0]);
            if (resp == 0) {
                GuerreiroServicos guerreiroS = ServicosFactory.getGuerreiroServicos();
                guerreiroS.deletarGuerreiro(id);
                addRowToTable();
                JOptionPane.showMessageDialog(this, "Guerreiro " + nome + " deletada com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Ok, delete cancelado pelo usuário.");
            }
            jbEditarGuerreiro.setVisible(false);
            jbDeletarGuerreiro.setVisible(false);
        }//fim da condição de deletar
        else {
            limpaCampos();
            jbDefault();
        }
    }//GEN-LAST:event_jbDeletarGuerreiroActionPerformed

    private void jbEditarGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarGuerreiroActionPerformed
        // TODO add your handling code here:
        jbLimparGuerreiro.setEnabled(false);
        jbSalvarGuerreiro.setText("Atualizar");
        jbDeletarGuerreiro.setText("Cancelar");
        jrbFemininoGuerreiro.setVisible(false);
        jrbMasculinoGuerreiro.setVisible(false);
        jlSexoGuerreiro.setVisible(false);

        //buscar vítima e carregar nos campos
        int linha = jtGuerreiro.getSelectedRow();
        idEdit = (int) jtGuerreiro.getValueAt(linha, 0);
        GuerreiroServicos guerreiroS = ServicosFactory.getGuerreiroServicos();
        Guerreiro guerreiro = guerreiroS.getGuerreiroById(idEdit);
        //carrega na tela
        jtfNomeGuerreiro.setText(guerreiro.getNome());
        jtfOlhoGuerreiro.setText(guerreiro.getOlho());
        jtfCabeloGuerreiro.setText(guerreiro.getCabelo());
        jtfPeleGuerreiro.setText(guerreiro.getPele());
        jtfArmamentoGuerreiro.setText(guerreiro.getArmamento());
    }//GEN-LAST:event_jbEditarGuerreiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFGuerreiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFGuerreiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFGuerreiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFGuerreiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFGuerreiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexoGuerreiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbDeletarGuerreiro;
    private javax.swing.JButton jbEditarGuerreiro;
    private javax.swing.JButton jbLimparGuerreiro;
    private javax.swing.JButton jbSalvarGuerreiro;
    private javax.swing.JLabel jlSexoGuerreiro;
    private javax.swing.JRadioButton jrbFemininoGuerreiro;
    private javax.swing.JRadioButton jrbMasculinoGuerreiro;
    private javax.swing.JTable jtGuerreiro;
    private javax.swing.JTextField jtfArmamentoGuerreiro;
    private javax.swing.JTextField jtfCabeloGuerreiro;
    private javax.swing.JTextField jtfNomeGuerreiro;
    private javax.swing.JTextField jtfOlhoGuerreiro;
    private javax.swing.JTextField jtfPeleGuerreiro;
    // End of variables declaration//GEN-END:variables
}
