/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Pessoa;
import servicos.ServicosFactory;
import servicos.VitimaServicos;

/**
 *
 * @author 182310065
 */
public class JFVitima extends javax.swing.JFrame {

    int idEdit;

    /**
     * Creates new form JFVitima
     */
    public JFVitima() {
        initComponents();
        addRowToTable();
        jbEditarVitima.setVisible(false);
        jbDeletarVitima.setVisible(false);
    }

    private void addRowToTable() {
        //pega a modelagem da tabela na interface gráfica
        DefaultTableModel model = (DefaultTableModel) jtVitimas.getModel();
        model.getDataVector().removeAllElements(); //remove todas as linhas
        model.fireTableDataChanged();
        Object rowData[] = new Object[5];//cria vetor de cinco posições que corresponde às colunas da tabela vítima
        VitimaServicos vitimaS = ServicosFactory.getVitimaServicos(); //percorre lista, popula vetor e adiciona vetor à tabela
        for (Pessoa vitima : vitimaS.listaVitimas()) {
            rowData[0] = vitima.getId();
            rowData[1] = vitima.getNome();
            rowData[2] = vitima.getOlho();
            rowData[3] = vitima.isSexo() == false ? "FEMININO" : "MASCULINO"; //if operador ternário
            rowData[4] = vitima.getPontosDeVida();
            model.addRow(rowData);
        }
    }//fim addRowToTable

    private void limpaCampos() {
        jtfNomeVitima.setText("");
        jtfCabeloVitima.setText("");
        jtfOlhoVitima.setText("");
        jtfPeleVitima.setText("");
        bgSexoVitima.clearSelection();
        jtfNomeVitima.requestFocus();
    }

    private boolean validaInputs() {
        if (jtfNomeVitima.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher o nome");
            jtfNomeVitima.requestFocus();
            return false;
        }
        if (jtfCabeloVitima.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher o cabelo");
            jtfCabeloVitima.requestFocus();
            return false;
        }
        if (jtfOlhoVitima.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher o olho");
            jtfOlhoVitima.requestFocus();
            return false;
        }
        if (jtfPeleVitima.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencher a pele");
            jtfPeleVitima.requestFocus();
            return false;
        }
        if (!jrbFemininoVitima.isSelected() && !jrbMasculinoVitima.isSelected()) {
            JOptionPane.showMessageDialog(this, "Selecionar sexo");
            return false;
        }
        return true;
    }

    private void jbDefault() {
        jbSalvarVitima.setText("Salvar");
        jbDeletarVitima.setText("Deletar");
        jlSexoVitima.setVisible(true);
        jrbFemininoVitima.setVisible(true);
        jrbMasculinoVitima.setVisible(true);
        jbEditarVitima.setVisible(false);
        jbDeletarVitima.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexoVitima = new javax.swing.ButtonGroup();
        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jtfNomeVitima = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfCabeloVitima = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfOlhoVitima = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfPeleVitima = new javax.swing.JTextField();
        jrbFemininoVitima = new javax.swing.JRadioButton();
        jrbMasculinoVitima = new javax.swing.JRadioButton();
        jlSexoVitima = new javax.swing.JLabel();
        jbSalvarVitima = new javax.swing.JButton();
        jbLimparVitima = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVitimas = new javax.swing.JTable();
        jbDeletarVitima = new javax.swing.JButton();
        jbEditarVitima = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Vítima");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 255));

        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Nome:");

        jtfNomeVitima.setToolTipText("Informe o nome da vítima");
        jtfNomeVitima.setName(""); // NOI18N

        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Cabelo:");

        jtfCabeloVitima.setToolTipText("Informe a cor do cabelo da vítima.");

        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("Olho:");

        jtfOlhoVitima.setToolTipText("Informe a cor do olho da vítima.");

        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("Pele:");

        jtfPeleVitima.setToolTipText("Informe a cor de pele da vítima.");

        bgSexoVitima.add(jrbFemininoVitima);
        jrbFemininoVitima.setForeground(new java.awt.Color(153, 153, 255));
        jrbFemininoVitima.setText("Feminino");

        bgSexoVitima.add(jrbMasculinoVitima);
        jrbMasculinoVitima.setForeground(new java.awt.Color(153, 153, 255));
        jrbMasculinoVitima.setText("Masculino");

        jlSexoVitima.setForeground(new java.awt.Color(153, 153, 255));
        jlSexoVitima.setText("Sexo:");

        jbSalvarVitima.setBackground(new java.awt.Color(204, 204, 255));
        jbSalvarVitima.setForeground(new java.awt.Color(102, 102, 255));
        jbSalvarVitima.setText("Salvar");
        jbSalvarVitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarVitimaActionPerformed(evt);
            }
        });

        jbLimparVitima.setBackground(new java.awt.Color(204, 204, 255));
        jbLimparVitima.setForeground(new java.awt.Color(102, 102, 255));
        jbLimparVitima.setText("Limpar");
        jbLimparVitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparVitimaActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(204, 204, 255));

        jtVitimas.setForeground(new java.awt.Color(153, 153, 255));
        jtVitimas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Olho", "Sexo", "HP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVitimas.setGridColor(new java.awt.Color(204, 204, 255));
        jtVitimas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtVitimasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtVitimas);
        if (jtVitimas.getColumnModel().getColumnCount() > 0) {
            jtVitimas.getColumnModel().getColumn(0).setResizable(false);
            jtVitimas.getColumnModel().getColumn(1).setResizable(false);
            jtVitimas.getColumnModel().getColumn(2).setResizable(false);
            jtVitimas.getColumnModel().getColumn(3).setResizable(false);
            jtVitimas.getColumnModel().getColumn(4).setResizable(false);
        }

        jbDeletarVitima.setBackground(new java.awt.Color(204, 204, 255));
        jbDeletarVitima.setForeground(new java.awt.Color(102, 102, 255));
        jbDeletarVitima.setText("Deletar");
        jbDeletarVitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarVitimaActionPerformed(evt);
            }
        });

        jbEditarVitima.setBackground(new java.awt.Color(204, 204, 255));
        jbEditarVitima.setForeground(new java.awt.Color(102, 102, 255));
        jbEditarVitima.setText("Editar");
        jbEditarVitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarVitimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtfNomeVitima, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtfPeleVitima, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jtfCabeloVitima, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jlSexoVitima))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addComponent(jtfOlhoVitima, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jrbMasculinoVitima, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jrbFemininoVitima))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbSalvarVitima)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbLimparVitima)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbEditarVitima)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbDeletarVitima)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNomeVitima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCabeloVitima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtfOlhoVitima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfPeleVitima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSexoVitima)
                    .addComponent(jrbFemininoVitima))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbMasculinoVitima, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarVitima)
                    .addComponent(jbLimparVitima)
                    .addComponent(jbEditarVitima)
                    .addComponent(jbDeletarVitima))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimparVitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparVitimaActionPerformed
        // TODO add your handling code here:
        limpaCampos();
    }//GEN-LAST:event_jbLimparVitimaActionPerformed

    private void jbSalvarVitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarVitimaActionPerformed
        // TODO add your handling code here:
        if (jbSalvarVitima.getText().equals("Salvar")) {
            if (validaInputs()) {
                Pessoa v = new Pessoa();
                v.setNome(jtfNomeVitima.getText().toUpperCase());
                v.setOlho(jtfOlhoVitima.getText().toUpperCase());
                v.setCabelo(jtfCabeloVitima.getText().toUpperCase());
                v.setPele(jtfPeleVitima.getText().toUpperCase());
                if (jrbFemininoVitima.isSelected() || jrbMasculinoVitima.isSelected()) {
                    v.setSexo(!jrbFemininoVitima.isSelected());
                }
                VitimaServicos vitimaS = ServicosFactory.getVitimaServicos();
                vitimaS.cadastrarVitima(v);
                addRowToTable();
                limpaCampos();
            }
        }//fim da condição de salvar
        else {
            Pessoa vit = new Pessoa();
            vit.setId(idEdit);
            vit.setNome(jtfNomeVitima.getText());
            vit.setOlho(jtfOlhoVitima.getText());
            vit.setCabelo(jtfCabeloVitima.getText());
            vit.setPele(jtfPeleVitima.getText());
            VitimaServicos vitimaS = ServicosFactory.getVitimaServicos();
            vitimaS.atualizarVitima(vit);
            addRowToTable();
            JOptionPane.showMessageDialog(this, "Vítima atualizada com sucesso!");
            jbDefault();
            limpaCampos();
        }//fim da condição de atualizar
    }//GEN-LAST:event_jbSalvarVitimaActionPerformed

    private void jbDeletarVitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarVitimaActionPerformed
        // TODO add your handling code here:
        if (jbDeletarVitima.getText().equals("Deletar")) {
            int linha = jtVitimas.getSelectedRow();
            int id = (int) jtVitimas.getValueAt(linha, 0);
            String nome = (String) jtVitimas.getValueAt(linha, 1);
            Object[] btnMSG = {"Sim", "Não"};
            int resp = JOptionPane.showOptionDialog(this,
                    "Deseja realmente deletar " + nome,
                    ".: Deletar :.",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.WARNING_MESSAGE,
                    null, btnMSG, btnMSG[0]);
            if (resp == 0) {
                VitimaServicos vitimaS = ServicosFactory.getVitimaServicos();
                vitimaS.deletarVitima(id);
                addRowToTable();
                JOptionPane.showMessageDialog(this, "Vítima " + nome + " deletada com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Ok, delete cancelado pelo usuário.");
            }
            jbEditarVitima.setVisible(false);
            jbDeletarVitima.setVisible(false);
        }//fim da condição de deletar
        else {
            limpaCampos();
            jbDefault();
        }
    }//GEN-LAST:event_jbDeletarVitimaActionPerformed

    private void jbEditarVitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarVitimaActionPerformed
        // TODO add your handling code here:
        jbLimparVitima.setEnabled(false);
        jbSalvarVitima.setText("Atualizar");
        jbDeletarVitima.setText("Cancelar");
        jrbFemininoVitima.setVisible(false);
        jrbMasculinoVitima.setVisible(false);
        jlSexoVitima.setVisible(false);

        //buscar vítima e carregar nos campos
        int linha = jtVitimas.getSelectedRow();
        idEdit = (int) jtVitimas.getValueAt(linha, 0);
        VitimaServicos vitimaS = ServicosFactory.getVitimaServicos();
        Pessoa vitima = vitimaS.getVitimaById(idEdit);
        //carrega na tela
        jtfNomeVitima.setText(vitima.getNome());
        jtfOlhoVitima.setText(vitima.getOlho());
        jtfCabeloVitima.setText(vitima.getCabelo());
        jtfPeleVitima.setText(vitima.getPele());

    }//GEN-LAST:event_jbEditarVitimaActionPerformed

    private void jtVitimasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVitimasMouseClicked
        // TODO add your handling code here:
        jbEditarVitima.setVisible(true);
        jbDeletarVitima.setVisible(true);
    }//GEN-LAST:event_jtVitimasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVitima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVitima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVitima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVitima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVitima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexoVitima;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbDeletarVitima;
    private javax.swing.JButton jbEditarVitima;
    private javax.swing.JButton jbLimparVitima;
    private javax.swing.JButton jbSalvarVitima;
    private javax.swing.JLabel jlSexoVitima;
    private javax.swing.JRadioButton jrbFemininoVitima;
    private javax.swing.JRadioButton jrbMasculinoVitima;
    private javax.swing.JTable jtVitimas;
    private javax.swing.JTextField jtfCabeloVitima;
    private javax.swing.JTextField jtfNomeVitima;
    private javax.swing.JTextField jtfOlhoVitima;
    private javax.swing.JTextField jtfPeleVitima;
    // End of variables declaration//GEN-END:variables
}
